name: graphviz-wasm
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10
  - nodejs >=20
  - cmake >=3.24
  - make
  - emscripten =3.1.58
  - binaryen =117
  - fastapi
  - uvicorn-standard
  - gfaidx
